[package]
name = "js_bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { version = "0.3.76", features = [
    "Document",
    "Window",
    "Node",
    "HtmlElement",
] }